apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-init-script-config
  namespace: log-app
data:
  init.sql: |-
    CREATE TABLE IF NOT EXISTS counter (
      id SERIAL PRIMARY KEY,
      content TEXT NOT NULL DEFAULT ''
    )