apiVersion: v1
kind: Secret
metadata:
    name: postgres-secret
    namespace: log-app
type: Opaque
data:
    POSTGRES_DB: ENC[AES256_GCM,data:F3e+Jg==,iv:ibvi6yYO9WHucVxez+zEXRk6C7cAauJkeSIw960+GoA=,tag:zch7U3TdwOHj1eJlsA00sA==,type:str]
    POSTGRES_USER: ENC[AES256_GCM,data:fNbccezSyyP1EbvR08dks7ulDc0=,iv:VXcWiU4AdcHidRawhNb3ldCZtTtnbas46gMgTvlLl7Q=,tag:8fsFA795KCiWGlIPmhDYsg==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:tWDsq07HRCrQAFAxs3ORCGkKpnA=,iv:rVBPWmxuOVj1QlKUQRSW5iEocG5ZxO9AbVZSWxc73tw=,tag:dRrPefLgrMP29OV3KPNUEw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1sz5fw9x3yc6mmlmsva7nxrvh8r4nrke5yxrm9svm5swv0fk0dqsslv0t3j
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFTnhFQmc3ZU0wTm95VU4x
            cC8vM1NNMHRjcEJmbkxqOWpzVkRFeDI3a1hnCmlmd1V0VitvZnZtRlJTV3pYMVYw
            dmp1MTg2QmU0RkRqWS9rS2hZeGJOK1kKLS0tIHpTNGNiYXFGZHpUUEM0SzcyNC8y
            UVd3UjdTSzBUWUdXOVJkMjA3VkdQV2MKRvSgAYHeM/e3xvqqO2kbgNsINloV5LIX
            zVehWP/avlTz/l36mTz1scSgI9lAKv8MtoY96fCDv9dvMXSN7XVcHA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-06-09T23:49:37Z"
    mac: ENC[AES256_GCM,data:ZS0JfyNFpciJSsOEaNfrCwVJt7MLqYeycY9tB/ekPHJNpzRzC6PiPcQ+J8m247RBd/BIyWyhMmBUQskoVMSRw/ui5WdB6l4+PGbAWYKIKaVT1avUMmI6lfunRgl+zaDsPEj0q+L3s2aUppZhlFaMnm398fc7WrVTIbx2j/YL8Hk=,iv:+9+kjSXYnsP4buq964NBqBEWFhDmfiLGDmmPit2ivw0=,tag:nLG0uMTb2W88iblc2YrhJg==,type:str]
    pgp: []
    encrypted_regex: ^(data)$
    version: 3.7.3
