apiVersion: apps/v1
kind: Deployment
metadata:
  name: kube-ex1-01
  namespace: log-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: log-app
  template:
    metadata:
      labels:
        app: log-app
    spec:
      volumes:
        - name: shared-bucket
          persistentVolumeClaim:
            claimName: log-app-pv-claim
      containers:
        - name: log-writer-app
          image: jamesho287/kube-ex1-01:v0.5
          imagePullPolicy: IfNotPresent
          env:
            - name: PRODUCTION
              value: "true"
            - name: WRITER
              value: "true"
            - name: NS
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          volumeMounts:
            - name: shared-bucket
              mountPath: /usr/src/app/files
          envFrom:
          - secretRef:
              name: postgres-secret
        - name: log-reader-app
          image: jamesho287/kube-ex1-01:v0.5
          imagePullPolicy: IfNotPresent
          env:
            - name: PRODUCTION
              value: "true"
            - name: WRITER
              value: "false"
            - name: NS
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            # Import individual env variable
            - name: GREETING_WORD
              valueFrom:
                configMapKeyRef:
                  name: log-app-config-1
                  key: greeting.word
          # Import env variable in batch
          envFrom:
          - configMapRef:
              name: log-app-config-2
          - secretRef:
              name: postgres-secret
          volumeMounts:
            - name: shared-bucket
              mountPath: /usr/src/app/files