apiVersion: apps/v1
kind: Deployment
metadata:
  name: kube-ex1-01
  namespace: log-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: log-app
  template:
    metadata:
      labels:
        app: log-app
    spec:
      containers:
        - name: log-writer-app
          image: jamesho287/kube-ex1-01:v0.7
          imagePullPolicy: Always
          resources:
            limits:
              cpu: "100m"
              memory: "100Mi"
          env:
            - name: PRODUCTION
              value: "true"
            - name: WRITER
              value: "true"
            - name: NS
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          envFrom:
          - secretRef:
              name: postgres-secret
        - name: log-reader-app
          image: jamesho287/kube-ex1-01:v0.7
          imagePullPolicy: Always
          ports:
          - name: readiness-port
            containerPort: 3400
          - name: server-port
            containerPort: 3400
          readinessProbe:
            initialDelaySeconds: 30
            periodSeconds: 10
            successThreshold: 2
            failureThreshold: 5
            # timeoutSeconds: 5
            httpGet:
              path: /healthz
              port: readiness-port
              # httpHeaders:
              # - name: healthcheck
              #   value: "1"
          resources:
            limits:
              cpu: "100m"
              memory: "100Mi"
          env:
            - name: PRODUCTION
              value: "true"
            - name: WRITER
              value: "false"
            - name: NS
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            # Import individual env variable
            - name: GREETING_WORD
              valueFrom:
                configMapKeyRef:
                  name: log-app-config-1
                  key: greeting.word
          # Import env variable in batch
          envFrom:
          - configMapRef:
              name: log-app-config-2
          - secretRef:
              name: postgres-secret