apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: log-app-ingress
  namespace: log-app
  annotations:
    kubernetes.io/ingress.class: traefik
    traefik.ingress.kubernetes.io/router.entrypoints: web
    ingress.kubernetes.io/ssl-redirect: "false"
spec:
  rules:
  - host: localhost
    http:
      paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: log-app-svc
              port:
                number: 8080