apiVersion: v1
kind: Service
metadata:
  name: log-app-svc
  namespace: log-app
spec:
  type: ClusterIP
  selector:
    app: log-app
  ports:
    - port: 8004
      protocol: TCP
      targetPort: 3400