apiVersion: v1
kind: Service
metadata:
  name: kube-ex1-01
  namespace: log-app
spec:
  type: NodePort
  selector:
    app: log-app
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 3400